name: mobile_wedding_invitation
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2
  flutter_inappwebview: ^6.1.5
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC/AmaticSC-Regular.ttf
        - asset: assets/fonts/AmaticSC/AmaticSC-Bold.ttf
    - family: GowunBatang
      fonts:
        - asset: assets/fonts/GowunBatang/GowunBatang-Regular.ttf
        - asset: assets/fonts/GowunBatang/GowunBatang-Bold.ttf

flutter_gen:
  output: lib/gen/ # 생성된 파일이 저장될 위치
  line_length: 80

  # SVG 패키지와 연동하여 .svg() 메소드를 자동 생성
  integrations:
    flutter_svg: true
