name: mobile_wedding_invitation
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC/AmaticSC-Regular.ttf
        - asset: assets/fonts/AmaticSC/AmaticSC-Bold.ttf
    - family: GowunBatang
      fonts:
        - asset: assets/fonts/GowunBatang/GowunBatang-Regular.ttf
        - asset: assets/fonts/GowunBatang/GowunBatang-Bold.ttf

flutter_gen:
  output: lib/gen/ # 생성된 파일이 저장될 위치
  line_length: 80
